ALTER TABLE channels
  ADD COLUMN IF NOT EXISTS archived TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE chat_messages
  ADD COLUMN IF NOT EXISTS channel_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS country_code CHAR(2) NULL,
  ADD COLUMN IF NOT EXISTS user_avatar VARCHAR(255) NULL;
