[program:kidsmaster-worker]
command=/usr/bin/php /var/www/kidsmaster/workers/worker.php
directory=/var/www/kidsmaster
autostart=true
autorestart=true
startretries=3
stdout_logfile=/var/log/kidsmaster-worker.out.log
stderr_logfile=/var/log/kidsmaster-worker.err.log
user=www-data
environment=KM_ENV="production"
